apiVersion: 1

datasources:
  - name: Prometheus
    uid: ishtech-springboot-books-prometheus
    type: prometheus
    access: proxy
    url: http://ishtech-springboot-books-prometheus:9090
    isDefault: true
    editable: false
